### PR TITLE
FEA add listbox example

### PR DESCRIPTION
**Pull request by daz10000**
This adds in a working listbox with add/remove/doubleclick support.  I also took the opportunity to drop in the tabs, so you can tab through the counter and listbox example.  This should make it easy to slowly extend out to add a gallery of all the controls.  I ran out of time today, but I have a working editor demo, and want some slider / button example.  Would be nice to have a button to go the the relevant code for example example.  Works on desktop and web nicely

image

image

### CODE REVIEW

**Comment by daz10000** [comment]
One other random thought - if this gets built out nicely,  it wouldn't be too hard to set it for CI and then putting the web build output onto the docs page would make for a nice live demo.

**Comment by JordanMarr** [comment]
Looks like i passed over this sample. 
would you mind merging the new page in with the latest changes?

**Comment by daz10000** [comment]
And I completely missed your reply - let me do that now.

**Comment by JordanMarr** [comment]
Very nice! Thank you for the sample work.

**Comment by daz10000** [comment]
Ah - I was going to still merge in the newer demos from the regular AvaloniaExample page - half way through that - involves updating a bunch of things which probably should be updated as well, so there might be more update to take.  I have it wired up but some changes broke a few things.  The wildly skewed versions for everything avalonia are frustrating right now -alpha -rc02 etc, and some packages haven't caught up.  The whole community would do well to just sit for a while and have everyone update.

**Comment by JordanMarr** [comment]
My apologies! I should not have been so hasty to merge.

 Yes, I noticed when I was in there yesterday that the other sample project was broken until I updated to all the final release versions of Avalonia. Fortunately, updating to the latest and greatest of everything worked with no issues.

**Pull request merged**
