### PR TITLE
Update AvaloniaExample to include LiveCharts2 ColumnSeries chart

### PR DESCRIPTION
**Pull request by houstonhaynes**
Updated AvaloniaExample app to include a Chart view created from a LiveCharts2 sample. 

Screenshot 2023-06-30 at 9 04 26 AM

### CODE REVIEW

**Comment by JordanMarr** [comment]
Is this ready to merge, or still a WIP?

**Comment by houstonhaynes** [comment]
It's ready. Thanks!

**Comment by JordanMarr** [comment]
A great addition to the samples. Thanks!

**Comment by houstonhaynes** [comment]
Thanks so much for coaching me through it! I learned so much I hope I remember it all ❗ 😄

**Comment by daz10000** [comment]
On Sun, Jul 02, 2023 at 10:09:56AM -0700, Houston Haynes wrote:
> Thanks so much for coaching me through it! I learned so much I hope I remember it all ❗ 😄 
> 

That's why we have the example gallery, so you don't have to remember it all :) - just cut and paste.. cut and paste..

**Pull request merged**
